# Generated by Django 4.2.30 on 2026-09-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listing_approved_at_listing_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='approved_by',
        ),
    ]
