# Generated by Django 4.2.30 on 2026-09-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Контактная информация для арендаторов'),
        ),
    ]
