# Generated by Django 4.2.30 on 2026-10-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
