# Generated by Django 4.2.30 on 2026-10-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
