# Generated by Django 4.2.30 on 2026-10-07 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_delete_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='renter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listing'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
